# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStreet', models.CharField(max_length=25)),
                ('jobCity', models.CharField(max_length=20)),
                ('jobState', models.CharField(max_length=2)),
                ('jobZipcode', models.CharField(max_length=5)),
                ('access', models.CharField(max_length=20)),
                ('stories', models.IntegerField(max_length=2)),
                ('notes', models.TextField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='billState',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='billStreet',
            field=models.CharField(max_length=25),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customers.Customer'),
        ),
    ]
